spring.application.name=zenq

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/zenq
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=zenq
spring.datasource.password=zenq
spring.jpa.hibernate.ddl-auto=update
